
CREATE TABLE traffic_volume (
    TIS_ID INT   NOT NULL,
    HMGNS_LNK_ID INT   NOT NULL,
    HMGNS_FLOW_ID INT   NOT NULL,
    LGA_SHORT_NM VARCHAR(30)   NOT NULL,
    RGN_LONG_NM VARCHAR(255)   NOT NULL,
    ROAD_NBR INT   NOT NULL,
    DAILY_AVG_VEHICLES INT   NOT NULL,
    FLOW VARCHAR(30)   NOT NULL,
    CONSTRAINT pk_traffic_volume PRIMARY KEY (
        TIS_ID
     )
);

CREATE TABLE hmgns_flow (
    TIS_ID INT   NOT NULL,
    TIS_ROUTE INT   NOT NULL,
    TIS_DESC VARCHAR(255)   NOT NULL,
    MIDPNT_LAT VARCHAR(30)   NOT NULL,
    MIDPNT_LON VARCHAR(30)   NOT NULL,
    DT_MODIFIE VARCHAR(30)   NOT NULL,
    DT_CREATED VARCHAR(30)   NOT NULL,
    HMGNS_FL_1 VARCHAR(10)   NOT NULL,
    ROAD_NBR INT   NOT NULL,
    LRS_ROAD_1 VARCHAR(30)   NOT NULL,
    CONSTRAINT pk_hmgns_flow PRIMARY KEY (
        TIS_ID
     )
);

CREATE TABLE hourly_volume (
    HMGNS_LNK_ID INT   NOT NULL,
    HMGNS_FLOW_ID INT   NOT NULL,
    PERIOD_TYPE VARCHAR(30)   NOT NULL,
    T00 INT   NOT NULL,
    T01 INT   NOT NULL,
    T02 INT   NOT NULL,
    T03 INT   NOT NULL,
    T04 INT   NOT NULL,
    T05 INT   NOT NULL,
    T06 INT   NOT NULL,
    T07 INT   NOT NULL,
    T08 INT   NOT NULL,
    T09 INT   NOT NULL,
    T10 INT   NOT NULL,
    T11 INT   NOT NULL,
    T12 INT   NOT NULL,
    T13 INT   NOT NULL,
    T14 INT   NOT NULL,
    T15 INT   NOT NULL,
    T16 INT   NOT NULL,
    T17 INT   NOT NULL,
    T18 INT   NOT NULL,
    T19 INT   NOT NULL,
    T20 INT   NOT NULL,
    T21 INT   NOT NULL,
    T22 INT   NOT NULL,
    T23 INT   NOT NULL
);

